# version: '1.0'
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        - COMPOSER_AUTH={"github-oauth":{"github.com":"${GITHUB_TOKEN}"}}
      no_cache: true
    env_file:
      - .env
    image: pkt-starter-kit
    container_name: pkt-starter-kit
    restart: always
    ports:
      - 44080:80
      - 44443:443
    volumes:
      - .:/var/www/html